name: Docker

on: [push, pull_request, workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Docker containers
      run: |
        set -x && \
        docker-compose up -d db && sleep 10 && \
        docker-compose up -d server && sleep 10 && \
        docker-compose up -d
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up pipenv
      run: set -x && pip install pipenv && pipenv sync
    - name: Run integration tests
      run: pipenv run test
    - name: Docker Log
      run: docker-compose logs -t
